### ISSUE TITLE
Plot:Legend DependencyProperties not working

### ISSUE THREAD

**Issue by isbeorn** [oxyplot/oxyplot-contrib#12]
Hello,

I have tried to update to Oxyplot 2.1.0, but facing an issue with the legends of Plots.
It seems this has been moved into a sub class, however when binding a dependency property to the Legend properties it will fail.
```
<oxy:Plot.Legends>
    <oxy:Legend
        LegendBackground="{Binding Path=Color, Source={StaticResource BackgroundBrush}}"
        LegendBorder="{Binding Path=Color, Source={StaticResource BorderBrush}}"
        LegendOrientation="Vertical"
        LegendPosition="LeftTop"
        LegendTextColor="{Binding Path=Color, Source={StaticResource PrimaryBrush}}" />
</oxy:Plot.Legends>

'A 'Binding' cannot be set on the 'LegendBackground' property of type 'Legend'. A 'Binding' can only be set on a DependencyProperty of a DependencyObject.'
```

My suspicion is that due to the refactoring the register was not done correctly and it is still registered to type Plot instead of type Legend: https://github.com/oxyplot/oxyplot-contrib/blob/develop/Source/OxyPlot.Contrib.Wpf/Legends/Legend.Properties.cs

Is this assumption correct and can this be fixed?

Thanks.

**Comment by VisualMelon** [comment]
Should be fixed now

**Comment by tonik173** [comment]
Hi, any hints when this fix is released? Thanks, Toni

**Comment by VisualMelon** [comment]
I had intended to release a 2.1.2 last weekend, but didn't get around to it; possibly this weekend.

(a candidate for release is at https://www.myget.org/feed/melonoxyplottesting/package/nuget/OxyPlot.Contrib.Wpf/2.1.2 if you wanted to test; but you shouldn't depend on that feed)

**Comment by isbeorn** [comment]
Thank you for the nuget update. Works like a charm now.

**Comment by VisualMelon** [comment]
@isbeorn so you know, also pushed to nuget proper: https://www.nuget.org/packages/OxyPlot.Contrib.Wpf
