### ISSUE TITLE
Packages not pushed to MyGet

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot-contrib#4]
Packages are not currently pushed to MyGet. This is presumably because there is no secret corresponding to an authentication token in this repository (appveyer.yml contains the secret from the OxyPlot repo).

**Comment by objorke** [comment]
I think the MyGet API key is correct. 
The API key was retrieved here: https://www.myget.org/profile/Me#!/AccessTokens
And encrypted on my account from this page: https://ci.appveyor.com/account/objorke/tools/encrypt

**Comment by objorke** [comment]
But it seems to not find any .nupkg files
https://ci.appveyor.com/project/objorke/oxyplot-contrib

**Comment by VisualMelon** [comment]
Oh, sorry. I really should been able to work that out.

**Comment by VisualMelon** [comment]
Fixed with #5
